### ISSUE TITLE
JSON keys: use lowercase snake_case instead of UPPERCASE SNAKE_CASE?

### ISSUE THREAD

**Issue by david-a-wheeler** [boyski/pmaudit#10]
Pure style question.  JSON keys can be anything, so the current convention works.

However, I think lowercase snake_case is more common than UPPERCASE SNAKE_CASE.

What do you think about switching to lowercase snake_case?

**Comment by boyski** [comment]
I have no significant opinion here. Feel free to change it to what you like.

**Comment by david-a-wheeler** [comment]
An implementation has been merged, so I'm closing this issue.
