### ISSUE TITLE
pmaudit should create empty depsfile

### ISSUE THREAD

**Issue by david-a-wheeler** [boyski/pmaudit#2]
If pmaudit is asked to create a depsfile, it silently doesn't do so if there's nothing to say.

That's odd, and if in a Makefile it'll look like the dependencies weren't considered at all.

I think it should always create the file, even if it will have no content.

**Comment by boyski** [comment]
Agreed.

**Comment by david-a-wheeler** [comment]
For pmaudit this is resolved in PR #1.

**Comment by david-a-wheeler** [comment]
For pmash this is resolved in PR #6.
