### ISSUE TITLE
CMD_AS_LIST

### ISSUE THREAD

**Issue by david-a-wheeler** [boyski/pmaudit#8]
I think providing "CMD" as a string is useful, but the space merging can hide exactly where the parameters are.

I propose adding another parameter, CMD_AS_LIST, the provides the exact CMD run as a list of parameters. Then you can see whatever detail you want.

**Comment by boyski** [comment]
OK.

**Comment by david-a-wheeler** [comment]
I created a draft pull request, where ended up naming it as "final_cmd" instead.  The "list" is just the data structure, the real issue is that it's the exact full final command that was executed (cmd, instead, is a user-visible easy representation of what was run).

**Comment by david-a-wheeler** [comment]
We have this, so I'm closing the issue.
